/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface BridgeInterface extends Interface {
    getFunction(nameOrSignature: "bridge" | "destChainId" | "mode" | "outboundNonce" | "processedNonces" | "relayer" | "release" | "token"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "BridgeInitiated" | "BridgeReleased"): EventFragment;

    encodeFunctionData(functionFragment: 'bridge', values: [BigNumberish, AddressLike]): string;
encodeFunctionData(functionFragment: 'destChainId', values?: undefined): string;
encodeFunctionData(functionFragment: 'mode', values?: undefined): string;
encodeFunctionData(functionFragment: 'outboundNonce', values?: undefined): string;
encodeFunctionData(functionFragment: 'processedNonces', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'relayer', values?: undefined): string;
encodeFunctionData(functionFragment: 'release', values: [AddressLike, BigNumberish, BigNumberish, BytesLike]): string;
encodeFunctionData(functionFragment: 'token', values?: undefined): string;

    decodeFunctionResult(functionFragment: 'bridge', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'destChainId', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'mode', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'outboundNonce', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'processedNonces', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'relayer', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'release', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'token', data: BytesLike): Result;
  }

  
    export namespace BridgeInitiatedEvent {
      export type InputTuple = [sender: AddressLike, recipient: AddressLike, amount: BigNumberish, nonce: BigNumberish];
      export type OutputTuple = [sender: string, recipient: string, amount: bigint, nonce: bigint];
      export interface OutputObject {sender: string, recipient: string, amount: bigint, nonce: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace BridgeReleasedEvent {
      export type InputTuple = [recipient: AddressLike, amount: BigNumberish, nonce: BigNumberish];
      export type OutputTuple = [recipient: string, amount: bigint, nonce: bigint];
      export interface OutputObject {recipient: string, amount: bigint, nonce: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface Bridge extends BaseContract {
    
    connect(runner?: ContractRunner | null): Bridge;
    waitForDeployment(): Promise<this>;

    interface: BridgeInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    bridge: TypedContractMethod<
      [amount: BigNumberish, recipient: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    destChainId: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    mode: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    outboundNonce: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    processedNonces: TypedContractMethod<
      [arg0: BigNumberish, ],
      [boolean],
      'view'
    >
    

    
    relayer: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    release: TypedContractMethod<
      [recipient: AddressLike, amount: BigNumberish, nonce: BigNumberish, sig: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    token: TypedContractMethod<
      [],
      [string],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'bridge'): TypedContractMethod<
      [amount: BigNumberish, recipient: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'destChainId'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'mode'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'outboundNonce'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'processedNonces'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'relayer'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'release'): TypedContractMethod<
      [recipient: AddressLike, amount: BigNumberish, nonce: BigNumberish, sig: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'token'): TypedContractMethod<
      [],
      [string],
      'view'
    >;

    getEvent(key: 'BridgeInitiated'): TypedContractEvent<BridgeInitiatedEvent.InputTuple, BridgeInitiatedEvent.OutputTuple, BridgeInitiatedEvent.OutputObject>;
getEvent(key: 'BridgeReleased'): TypedContractEvent<BridgeReleasedEvent.InputTuple, BridgeReleasedEvent.OutputTuple, BridgeReleasedEvent.OutputObject>;

    filters: {
      
      'BridgeInitiated(address,address,uint256,uint256)': TypedContractEvent<BridgeInitiatedEvent.InputTuple, BridgeInitiatedEvent.OutputTuple, BridgeInitiatedEvent.OutputObject>;
      BridgeInitiated: TypedContractEvent<BridgeInitiatedEvent.InputTuple, BridgeInitiatedEvent.OutputTuple, BridgeInitiatedEvent.OutputObject>;
    

      'BridgeReleased(address,uint256,uint256)': TypedContractEvent<BridgeReleasedEvent.InputTuple, BridgeReleasedEvent.OutputTuple, BridgeReleasedEvent.OutputObject>;
      BridgeReleased: TypedContractEvent<BridgeReleasedEvent.InputTuple, BridgeReleasedEvent.OutputTuple, BridgeReleasedEvent.OutputObject>;
    
    };
  }