/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface BridgeInterface extends Interface {
    getFunction(nameOrSignature: "bridge" | "claim" | "destChainId" | "merkleRoot" | "mode" | "outboundNonce" | "processedNonces" | "relayer" | "setMerkleRoot" | "token" | "validRoots"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "BridgeClaimed" | "BridgeInitiated" | "MerkleRootUpdated"): EventFragment;

    encodeFunctionData(functionFragment: 'bridge', values: [BigNumberish, AddressLike]): string;
encodeFunctionData(functionFragment: 'claim', values: [BytesLike[], BytesLike, AddressLike, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'destChainId', values?: undefined): string;
encodeFunctionData(functionFragment: 'merkleRoot', values?: undefined): string;
encodeFunctionData(functionFragment: 'mode', values?: undefined): string;
encodeFunctionData(functionFragment: 'outboundNonce', values?: undefined): string;
encodeFunctionData(functionFragment: 'processedNonces', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'relayer', values?: undefined): string;
encodeFunctionData(functionFragment: 'setMerkleRoot', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'token', values?: undefined): string;
encodeFunctionData(functionFragment: 'validRoots', values: [BytesLike]): string;

    decodeFunctionResult(functionFragment: 'bridge', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'claim', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'destChainId', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'merkleRoot', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'mode', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'outboundNonce', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'processedNonces', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'relayer', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setMerkleRoot', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'token', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'validRoots', data: BytesLike): Result;
  }

  
    export namespace BridgeClaimedEvent {
      export type InputTuple = [recipient: AddressLike, amount: BigNumberish, nonce: BigNumberish];
      export type OutputTuple = [recipient: string, amount: bigint, nonce: bigint];
      export interface OutputObject {recipient: string, amount: bigint, nonce: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace BridgeInitiatedEvent {
      export type InputTuple = [sender: AddressLike, recipient: AddressLike, amount: BigNumberish, nonce: BigNumberish];
      export type OutputTuple = [sender: string, recipient: string, amount: bigint, nonce: bigint];
      export interface OutputObject {sender: string, recipient: string, amount: bigint, nonce: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace MerkleRootUpdatedEvent {
      export type InputTuple = [root: BytesLike];
      export type OutputTuple = [root: string];
      export interface OutputObject {root: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface Bridge extends BaseContract {
    
    connect(runner?: ContractRunner | null): Bridge;
    waitForDeployment(): Promise<this>;

    interface: BridgeInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    bridge: TypedContractMethod<
      [amount: BigNumberish, recipient: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    claim: TypedContractMethod<
      [proof: BytesLike[], root: BytesLike, recipient: AddressLike, amount: BigNumberish, nonce: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    destChainId: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    merkleRoot: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    mode: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    outboundNonce: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    processedNonces: TypedContractMethod<
      [arg0: BigNumberish, ],
      [boolean],
      'view'
    >
    

    
    relayer: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    setMerkleRoot: TypedContractMethod<
      [root: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    token: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    validRoots: TypedContractMethod<
      [arg0: BytesLike, ],
      [boolean],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'bridge'): TypedContractMethod<
      [amount: BigNumberish, recipient: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'claim'): TypedContractMethod<
      [proof: BytesLike[], root: BytesLike, recipient: AddressLike, amount: BigNumberish, nonce: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'destChainId'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'merkleRoot'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'mode'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'outboundNonce'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'processedNonces'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'relayer'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'setMerkleRoot'): TypedContractMethod<
      [root: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'token'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'validRoots'): TypedContractMethod<
      [arg0: BytesLike, ],
      [boolean],
      'view'
    >;

    getEvent(key: 'BridgeClaimed'): TypedContractEvent<BridgeClaimedEvent.InputTuple, BridgeClaimedEvent.OutputTuple, BridgeClaimedEvent.OutputObject>;
getEvent(key: 'BridgeInitiated'): TypedContractEvent<BridgeInitiatedEvent.InputTuple, BridgeInitiatedEvent.OutputTuple, BridgeInitiatedEvent.OutputObject>;
getEvent(key: 'MerkleRootUpdated'): TypedContractEvent<MerkleRootUpdatedEvent.InputTuple, MerkleRootUpdatedEvent.OutputTuple, MerkleRootUpdatedEvent.OutputObject>;

    filters: {
      
      'BridgeClaimed(address,uint256,uint256)': TypedContractEvent<BridgeClaimedEvent.InputTuple, BridgeClaimedEvent.OutputTuple, BridgeClaimedEvent.OutputObject>;
      BridgeClaimed: TypedContractEvent<BridgeClaimedEvent.InputTuple, BridgeClaimedEvent.OutputTuple, BridgeClaimedEvent.OutputObject>;
    

      'BridgeInitiated(address,address,uint256,uint256)': TypedContractEvent<BridgeInitiatedEvent.InputTuple, BridgeInitiatedEvent.OutputTuple, BridgeInitiatedEvent.OutputObject>;
      BridgeInitiated: TypedContractEvent<BridgeInitiatedEvent.InputTuple, BridgeInitiatedEvent.OutputTuple, BridgeInitiatedEvent.OutputObject>;
    

      'MerkleRootUpdated(bytes32)': TypedContractEvent<MerkleRootUpdatedEvent.InputTuple, MerkleRootUpdatedEvent.OutputTuple, MerkleRootUpdatedEvent.OutputObject>;
      MerkleRootUpdated: TypedContractEvent<MerkleRootUpdatedEvent.InputTuple, MerkleRootUpdatedEvent.OutputTuple, MerkleRootUpdatedEvent.OutputObject>;
    
    };
  }